// File generated by FlutterFire CLI.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5yDECq2yLwO3QTvp5M4nadvh5RbrXaJc',
    appId: '1:404460330096:web:387545a15be2b13379a8b5',
    messagingSenderId: '404460330096',
    projectId: 'caserita-market',
    authDomain: 'caserita-market.firebaseapp.com',
    databaseURL: 'https://caserita-market-default-rtdb.firebaseio.com',
    storageBucket: 'caserita-market.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCI3gplE9UtSpVUmCd5O33IX3nhfEZhcE',
    appId: '1:404460330096:android:bf9cf286123fc98479a8b5',
    messagingSenderId: '404460330096',
    projectId: 'caserita-market',
    databaseURL: 'https://caserita-market-default-rtdb.firebaseio.com',
    storageBucket: 'caserita-market.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxNr3Rs7bUv3r7Lsc3eUOCoSglZ7p3SKk',
    appId: '1:404460330096:ios:80970533324afe6c79a8b5',
    messagingSenderId: '404460330096',
    projectId: 'caserita-market',
    databaseURL: 'https://caserita-market-default-rtdb.firebaseio.com',
    storageBucket: 'caserita-market.firebasestorage.app',
    iosClientId:
        '404460330096-irptpv1jhciccf4l5msona18irfm3ts8.apps.googleusercontent.com',
    iosBundleId: 'com.example.caseritaMarket',
  );
}
